### ISSUE TITLE
Check Session Management. 

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#10]
Are we using database sessions?  File sessions?  Need to check

Probably just need to change the following line:
    'driver' => env('SESSION_DRIVER', 'file'),

(add SESSION_DRIVER=file in local dev .env file)

See documentation: https://laravel.com/docs/9.x/session

**Comment by alikemaltanriverdi** [comment]
https://github.com/BinghamtonUniversity/IAMBing/commit/c2371e9810dfa144b76425cbe08341cff7545b5c is addresing this issue. We are currently using "file" as default session manager, so I have updated it to redis in order to our redis driver. I am still using 'file' as my local session driver

**Comment by timcortesi** [comment]
Looks fixed.  Marking as closed/complete
