### ISSUE TITLE
Check Permissions on Horizon

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#11]
Need to possibly add a gate?

See documentation: https://laravel.com/docs/9.x/horizon#dashboard-authorization

**Comment by timcortesi** [comment]
I tested this by opening the horizon view in an incognito window and was able to view everything without logging in.  This does not appear to be fixed.  Reassigning to @alikemaltanriverdi

**Comment by alikemaltanriverdi** [comment]
Tim, the permissions is not enforced in the local environment. Can you please confirm the environment? Environment used needs to be changed from "local" to "prod" or "test".

**Comment by timcortesi** [comment]
@alikemaltanriverdi confirmed working with 'prod' environment.  Marking as closed / complete
