### ISSUE TITLE
DataProxy: Implement Shadow Mode for Account Actions

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#14]
There are several APIs within IAM which allow the IAMBing system to perform the following actions against AD and Google Accounts:

- create/update account
- delete account

We need to figure out some sort of logging mechanism (for testing) which would log an event any time that:

- An account is added to a group
- An account is removed from a group
- An account is created
- An account is deleted

Log this wherever.. doesn't really matter. Maybe BTMP?

There should be a configuration option for "shadow mode" where everything is logged but nothing actually happens in Google or AD.

**Comment by alikemaltanriverdi** [comment]
done
