### ISSUE TITLE
"Merge Identity" needs to be implemented

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#3]
Should be able to select another identity (source identity) to merge into the current (target) identity.
This will then move all of the following from the source identity into the target identity:
- Groups
- Sponsorships
- Entitlements
- Affiliations
- Accounts

If the "Delete Source Identity" box is checked, the source identity should be deleted.

**Comment by alikemaltanriverdi** [comment]
Commit https://github.com/BinghamtonUniversity/IAMBing/commit/dbc3fc8773f792d3b8025b63b8be3397dbb06bcb addresses the issue

**Comment by timcortesi** [comment]
Looks good.  Marking as closed / complete
