### ISSUE TITLE
Make sure all BU attributes are being synced properly

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#35]
It doesn't look like all AD attributes are syncing properly.  Specifically edupersonaffiliation and edupersonprimaryaffiliation are ones that I noticed, but there may be othrs.

**Comment by alikemaltanriverdi** [comment]
@timcortesi **primary_affiliation** and **affiliations** attributes are missing from the request object, which causes for some of the attributes not to update in AD

**Comment by alikemaltanriverdi** [comment]
@timcortesi This is completed, and now syncing properly. You can close this if you'd like.

**Comment by timcortesi** [comment]
@alikemaltanriverdi We haven't tested this against production AD.  We need to come up with some sort of test to verify that this will work correctly in prod.
