### ISSUE TITLE
Implement Action Queue Policies and Permissions

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#37]
There should be a permission for viewing the action queue, and a permission for executing the action queue.

**Comment by alikemaltanriverdi** [comment]
https://github.com/BinghamtonUniversity/IAMBing/commit/3dcf9aa341b1a408f3d578e8e8e1167f5cf2cadd is addressing this issue. @timcortesi please let me know if there's anything you'd like me to updated

**Comment by alikemaltanriverdi** [comment]
https://github.com/BinghamtonUniversity/IAMBing/commit/d1276f2c0462045cd47ef1875ff3e2e1a6aa84fb commit addresses a bug that was causing the action queue to be visible even without the required permissions.

**Comment by timcortesi** [comment]
Marking as closed / complete
