### ISSUE TITLE
Add a "Download as CSV" button for the Group Action Queue

### ISSUE THREAD

**Issue by timcortesi** [BinghamtonUniversity/IAMBing#38]
Should include:

Action
First Name
Last Name
Group Name
Date
All Unique IDs (BNumber, Millennium ID, SUNY ID) <-- This should not be hard coded, they should be dynamic based on the configuration

**Comment by timcortesi** [comment]
@alikemaltanriverdi 

This implementation is overly complicated.  This should just be a simple CSV download with a hyperlink (no Javascript)

```php
return response($csv_data, 200)
        ->header('Content-Type', 'text/csv')
        ->header('Content-Disposition','filename="Group Action Queue '.$date.'"');
```

Filename should also include date and 'queue' is singular (not queues)

**Comment by alikemaltanriverdi** [comment]
@timcortesi Thank you for the feedback. I'll update the code make another commit.

**Comment by timcortesi** [comment]
Working as expected.  Closed
