### ISSUE TITLE
No Affiliations for a Group Returns Null in the User Self Dashboard

### ISSUE THREAD

**Issue by alikemaltanriverdi** [BinghamtonUniversity/IAMBing#44]
**Bug:**
When a group has not affiliations, the return value of the group affiliation is **null**, which places an empty space in the user's list of affiliations

**Expected:**
A group can have no affiliation, and it should not affect the user's dashboard

**Comment by timcortesi** [comment]
@alikemaltanriverdi -- Please test fix in 60988dc004e20e99d7ef0674fea653328676c0db

**Comment by alikemaltanriverdi** [comment]
@timcortesi confirmed, fixed
